apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-identity-wallets-new
spec:
  destination:
    name: ''
    namespace: product-managed-identity-wallets
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/managed-identity-wallet
    repoURL: 'https://github.com/catenax-ng/tx-managed-identity-wallets.git'
    targetRevision: features/java-did-web
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f values-int.yaml'
  sources: []
  project: project-managed-identity-wallets