version: 2
updates:
  # maintain dependencies for GitHub actions 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github_actions"

  # maintain dependencies for Gradle
  - package-ecosystem: "gradle" # checks build.gradle(.kts) and settings.gradle(.kts)
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "java"
