version: 3

dotenv:
  - 'local.env'

includes:
  check:
    taskfile: .tasks/check-tools.yaml
    internal: true
  docker:
    taskfile: .tasks/docker-{{OS}}.yaml

tasks:
  check-prerequisites:
    desc: Checks the local machine for all tools, which are used for MIW development
    cmds:
      - task: check:check-all

  unittest:
    desc: Executes helm unittests
    dir: charts/managed-identity-wallet
    cmds:
      - helm unittest .

  build-app:
    desc: Build the whole app
    cmds:
      - ./gradlew build -PgithubToken=$GITHUB_TOKEN $SKIP_GRADLE_TASKS_PARAM

  clean-all:
    desc: Cleans everything...
    cmds:
      - ./gradlew clean
      - task: docker:cleanup
