version: 3

dotenv:
  - 'dev.env'

tasks:
  runDevEnv:
    desc: Spin up local Docker environment
    dir: dev-assets/dev-containers
    cmds:
      - docker-compose up

  unittest:
    desc: Executes helm unittests
    dir: charts/managed-identity-wallet
    cmds:
      - helm unittest .