# /********************************************************************************
# * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License, Version 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# * License for the specific language governing permissions and limitations
# * under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

image:
  tag: "latest-java-did-web"

secrets:
  DB_USER_NAME: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#user>
  DB_PASSWORD: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#password>
  ENCRYPTION_KEY: 76a7834fb37e090c2789a9b1a76748d3
  KEYCLOAK_CLIENT_ID: <path:managed-identity-wallets/data/int/managed-identity-wallets-secrets#miw-auth-client-id>

envs:
  DB_HOST: managed-identity-wallets-new-postgresql
  MIW_HOST_NAME: managed-identity-wallets-new.int.demo.catena-x.net  # Depend on ingress host name (managed-identity-wallets-new.int.demo.catena-x.net)
  KEYCLOAK_REALM: CX-Central
  AUTH_SERVER_URL: https://centralidp.int.demo.catena-x.net/auth
  AUTHORITY_WALLET_DID: "did:web:managed-identity-wallets-new.int.demo.catena-x.net:BPNL000000000000"

ingress:
  enabled: true
  hosts:
    - host: managed-identity-wallets-new.int.demo.catena-x.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: miw-secret
      hosts:
        - managed-identity-wallets-new.int.demo.catena-x.net

postgresql:
  primary:
    initdb:
      password: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#postgres-password>
  auth:
    password: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#password>
    postgresPassword: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#postgres-password>
    username: <path:managed-identity-wallets/data/int/postgres-managed-identity-wallets-secret-config#user>