apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallet.fullname" . }}-postgresql
type: Opaque
stringData:
  password: {{ .Values.postgresql.secret.password | quote }}
  postgres-password: {{ .Values.postgresql.secret.postgrespassword | quote }}
  user: {{ .Values.postgresql.secret.user | quote }}
