name: Build images and push Acapy as GitHub Package

on:
  workflow_dispatch:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_acapy
  IMAGE_VERSION: 0.7.4

jobs:
  build-and-push-acapy-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        run: git clone https://github.com/hyperledger/aries-cloudagent-python.git && cd aries-cloudagent-python && git checkout 0.7.4

      - name: Login to GitHub Container Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        if: ${{ !env.ACT }}
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./aries-cloudagent-python
          file: ./aries-cloudagent-python/docker/Dockerfile.run
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}